CREATE TABLE grupo(
    id INT PRIMARY KEY,
    nombre VARCHAR(30) CHARACTER SET latin1 NOT NULL
);

CREATE TABLE tipo_tel(
    id INT PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL
);

CREATE TABLE contactos(
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    id_grupo INT DEFAULT 0 REFERENCES grupo (id) ON DELETE CASCADE ON UPDATE CASCADE,
    tipo_t INT DEFAULT 300 REFERENCES tipo_tel (id) ON DELETE CASCADE ON UPDATE CASCADE,
    numero INT NOT NULL,
    correo VARCHAR(50) DEFAULT 'no',
    direccion VARCHAR(60) DEFAULT 'no'
);
